# Generated by Django 5.2.16 on 2026-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(max_length=50)),
                ('epochs', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('final_loss', models.FloatField(blank=True, null=True)),
                ('loss_curve_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('confusion_matrix_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
